=== Realovka/task2-epam/src/main/resources/data/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://example.com/medicines"
        xmlns:tns="http://example.com/medicines"
        elementFormDefault="qualified">
  
  <element name="medicines">
    <complexType>
      <sequence>
        <element name="medicine" type="tns:Medicine" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  
  <complexType name="Medicine">
    <sequence>
      <element name="name" type="string"/>
      <element name="pharm" type="string"/>
      <element name="group" type="string"/>
      <element name="analog" type="tns:Analog" maxOccurs="unbounded"/>
      <element name="version" type="tns:Version" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="id" type="ID" use="required"/>
    <attribute name="original" type="string" use="optional" default="false"/>
  </complexType>

  <complexType name="Analog">
    <sequence>
      <element name="analog-name" type="string"/>
    </sequence>
  </complexType>

  <complexType name="Version">
    <sequence>
      <element name="form" type="string"/>
      <element name="certificate" type="tns:Certificate"/>
      <element name="package" type="tns:Package"/>
      <element name="dosage" type="tns:Dosage"/>
    </sequence>
  </complexType>

  <complexType name="Certificate">
    <sequence>
      <element name="number" type="string"/>
      <element name="issuance" type="date"/>
      <element name="expiration" type="date"/>
    </sequence>
  </complexType>

  <complexType name="Package">
    <sequence>
      <element name="type" type="string"/>
      <element name="number-in-package" type="int"/>
      <element name="price-per-package" type="double"/>
    </sequence>
  </complexType>

  <complexType name="Dosage">
    <sequence>
      <element name="drug-dosage" type="double"/>
      <element name="reception-multiplicity" type="int"/>
    </sequence>
  </complexType>

  <simpleType name="type">
    <restriction base="string">
      <enumeration value="tablet"/>
      <enumeration value="powder"/>
      <enumeration value="gel"/>
      <enumeration value="injection"/>
      <enumeration value="spray"/>
      <enumeration value="suppository"/>
      <enumeration value="syrup"/>
      <enumeration value="solution for inhalation"/>
      <enumeration value="capsule"/>
      <enumeration value="suspension"/>
    </restriction>
  </simpleType>

  <simpleType name="reception-multiplicity">
    <restriction base="int">
      <minExclusive value="1"/>
    </restriction>
  </simpleType>

  <simpleType name="expiration">
    <restriction base="date">
      <pattern value="([2][0][0-4]\d\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01]))|2050-01-01"/>
    </restriction>
  </simpleType>

</schema>

=== Realovka/task2-epam/src/main/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>


<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.сom/medicines medicines.xsd">

    <medicine id="1">
        <name>Enalapril-LF</name>
        <pharm>Lecfarm</pharm>
        <group>antihypertensive</group>
        <analog>
            <analog-name>Berlipril</analog-name>
        </analog>
        <analog>
            <analog-name>Enap</analog-name>
        </analog>
        <version>
            <form>tablet</form>
            <certificate>
                <number>1</number>
                <issuance>2020-06-02</issuance>
                <expiration>2020-06-02</expiration>
            </certificate>
            <package>
                <type>box</type>
                <number-in-package>30</number-in-package>
                <price-per-package>2.3</price-per-package>
            </package>
            <dosage>
                <drug-dosage>10</drug-dosage>
                <reception-multiplicity>1</reception-multiplicity>
            </dosage>
        </version>
    </medicine>


    <medicine id="2">
        <name>Ramilong</name>
        <pharm>Lecfarm</pharm>
        <group>antihypertensive</group>
        <analog>
            <analog-name>Hartil</analog-name>
        </analog>
        <analog>
            <analog-name>Tritatse</analog-name>
        </analog>
        <version>
            <form>tablet</form>
            <certificate>
                <number>1</number>
                <issuance>2020-06-02</issuance>
                <expiration>2020-06-02</expiration>
            </certificate>
            <package>
                <type>box</type>
                <number-in-package>30</number-in-package>
                <price-per-package>10.7</price-per-package>
            </package>
            <dosage>
                <drug-dosage>10</drug-dosage>
                <reception-multiplicity>1</reception-multiplicity>
            </dosage>
        </version>
    </medicine>


</medicines>

=== Realovka/task2-epam/src/test/resources/data/medicine_is_valid.xml
<?xml version="1.0" encoding="UTF-8"?>


<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://example.com/medicines"
           xsi:schemaLocation="http://example.com/medicines medicines.xsd">

    <medicine id="id1">
        <name>Enalapril-LF</name>
        <pharm>Lecfarm</pharm>
        <group>antihypertensive</group>
        <analog>
            <analog-name>Berlipril</analog-name>
        </analog>
        <analog>
            <analog-name>Enap</analog-name>
        </analog>
        <version>
            <form>tablet</form>
            <certificate>
                <number>20/03/1371</number>
                <issuance>2016-06-02</issuance>
                <expiration>2050-01-01</expiration>
            </certificate>
            <package>
                <type>blister</type>
                <number-in-package>30</number-in-package>
                <price-per-package>2.3</price-per-package>
            </package>
            <dosage>
                <drug-dosage>10</drug-dosage>
                <reception-multiplicity>1</reception-multiplicity>
            </dosage>
        </version>
    </medicine>
</medicines>
